load("@rules_cc//cc:defs.bzl", "cc_test")

cc_library(
    name = "utilities",
    srcs = [
            ],
    hdrs = [
            "safe_ptr.h",
            ],
    linkopts = ["-pthread"],
    visibility = ["//src:__pkg__"],
)
